# Generated by Django 6.0 on 2025-12-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodpost',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
